name: "Time Logger Add-On"
version: "1.0.4"
slug: "time_logger"
description: "A minimal add-on that logs the current time."
init: false
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
# startup: application
# boot: auto
# image: "local/time_logger"
options:
  mqtt_host: "localhost"
  mqtt_user: "default_user"
  mqtt_pass: "default_password"
schema:
  mqtt_host: str
  mqtt_user: str
  mqtt_pass: str
  