name: "Time Logger Add-On"
version: "1.2.0"
slug: "time_logger"
description: "Gammu-based modem monitor with SMS sending capability via MQTT."
init: false
arch:
  - amd64
  - armv7
  - armhf
  - aarch64

options:
  mqtt_host: "localhost"           # Default MQTT host
  mqtt_port: 1883                  # Default MQTT port
  mqtt_user: "default_user"        # Default MQTT username
  mqtt_pass: "default_password"    # Default MQTT password
  mqtt_topic: "home/time_logger"   # Default MQTT topic
  serial_port: "/dev/ttyUSB2"      # Default Serial Port

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  mqtt_topic: str
  serial_port:  str


# Add permissions for D-Bus and devices
host_dbus: true
full_access: true
# host_network: true

devices:
  - /dev/bus/usb
  - /dev/ttyACM*
  - /dev/ttyUSB*

#privileged: true