name: "Time Logger Add-On"
version: "1.0.6"
slug: "time_logger"
description: "A minimal add-on that logs the current time."
init: false
arch:
  - amd64
  - armv7
  - armhf
  - aarch64

options:
  mqtt_host: "localhost"           # Default MQTT host
  mqtt_port: 1883                  # Default MQTT port
  mqtt_user: "default_user"        # Default MQTT username
  mqtt_pass: "default_password"    # Default MQTT password
  mqtt_topic: "home/time_logger"   # Default MQTT topic

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  mqtt_topic: str
  